#!/bin/bash

# This function tests the program's output against an expected output
test_coin_exchange() {
    input=$1
    expected_output="Enter the number of cents: "$2
    output=$(echo $input | python3 coin_exchange.py)

    if [ "$output" == "$expected_output" ]; then
        echo "Test with input $input passed."
    else
        echo "Test with input $input failed. Expected '$expected_output' but got '$output'."
        exit 1
    fi
}

# Running tests
echo "Starting tests..."
test_coin_exchange 0 "0 quarter, 0 dime, 0 nickel, 0 penny"
test_coin_exchange 1 "0 quarter, 0 dime, 0 nickel, 1 penny"
test_coin_exchange 2 "0 quarter, 0 dime, 0 nickel, 2 penny"
test_coin_exchange 3 "0 quarter, 0 dime, 0 nickel, 3 penny"
test_coin_exchange 4 "0 quarter, 0 dime, 0 nickel, 4 penny"
test_coin_exchange 5 "0 quarter, 0 dime, 1 nickel, 0 penny"
test_coin_exchange 6 "0 quarter, 0 dime, 1 nickel, 1 penny"
test_coin_exchange 7 "0 quarter, 0 dime, 1 nickel, 2 penny"
test_coin_exchange 8 "0 quarter, 0 dime, 1 nickel, 3 penny"
test_coin_exchange 9 "0 quarter, 0 dime, 1 nickel, 4 penny"
test_coin_exchange 10 "0 quarter, 1 dime, 0 nickel, 0 penny"
test_coin_exchange 11 "0 quarter, 1 dime, 0 nickel, 1 penny"
test_coin_exchange 12 "0 quarter, 1 dime, 0 nickel, 2 penny"
test_coin_exchange 13 "0 quarter, 1 dime, 0 nickel, 3 penny"
test_coin_exchange 14 "0 quarter, 1 dime, 0 nickel, 4 penny"
test_coin_exchange 15 "0 quarter, 1 dime, 1 nickel, 0 penny"
test_coin_exchange 16 "0 quarter, 1 dime, 1 nickel, 1 penny"
test_coin_exchange 17 "0 quarter, 1 dime, 1 nickel, 2 penny"
test_coin_exchange 18 "0 quarter, 1 dime, 1 nickel, 3 penny"
test_coin_exchange 19 "0 quarter, 1 dime, 1 nickel, 4 penny"
test_coin_exchange 20 "0 quarter, 2 dime, 0 nickel, 0 penny"
test_coin_exchange 21 "0 quarter, 2 dime, 0 nickel, 1 penny"
test_coin_exchange 22 "0 quarter, 2 dime, 0 nickel, 2 penny"
test_coin_exchange 23 "0 quarter, 2 dime, 0 nickel, 3 penny"
test_coin_exchange 24 "0 quarter, 2 dime, 0 nickel, 4 penny"
test_coin_exchange 25 "1 quarter, 0 dime, 0 nickel, 0 penny"
test_coin_exchange 26 "1 quarter, 0 dime, 0 nickel, 1 penny"
test_coin_exchange 27 "1 quarter, 0 dime, 0 nickel, 2 penny"
test_coin_exchange 28 "1 quarter, 0 dime, 0 nickel, 3 penny"
test_coin_exchange 29 "1 quarter, 0 dime, 0 nickel, 4 penny"
test_coin_exchange 30 "1 quarter, 0 dime, 1 nickel, 0 penny"
test_coin_exchange 31 "1 quarter, 0 dime, 1 nickel, 1 penny"
test_coin_exchange 32 "1 quarter, 0 dime, 1 nickel, 2 penny"
test_coin_exchange 33 "1 quarter, 0 dime, 1 nickel, 3 penny"
test_coin_exchange 34 "1 quarter, 0 dime, 1 nickel, 4 penny"
test_coin_exchange 35 "1 quarter, 1 dime, 0 nickel, 0 penny"
test_coin_exchange 36 "1 quarter, 1 dime, 0 nickel, 1 penny"
test_coin_exchange 37 "1 quarter, 1 dime, 0 nickel, 2 penny"
test_coin_exchange 38 "1 quarter, 1 dime, 0 nickel, 3 penny"
test_coin_exchange 39 "1 quarter, 1 dime, 0 nickel, 4 penny"
test_coin_exchange 40 "1 quarter, 1 dime, 1 nickel, 0 penny"
test_coin_exchange 41 "1 quarter, 1 dime, 1 nickel, 1 penny"
test_coin_exchange 42 "1 quarter, 1 dime, 1 nickel, 2 penny"
test_coin_exchange 43 "1 quarter, 1 dime, 1 nickel, 3 penny"
test_coin_exchange 44 "1 quarter, 1 dime, 1 nickel, 4 penny"
test_coin_exchange 45 "1 quarter, 2 dime, 0 nickel, 0 penny"
test_coin_exchange 46 "1 quarter, 2 dime, 0 nickel, 1 penny"
test_coin_exchange 47 "1 quarter, 2 dime, 0 nickel, 2 penny"
test_coin_exchange 48 "1 quarter, 2 dime, 0 nickel, 3 penny"
test_coin_exchange 49 "1 quarter, 2 dime, 0 nickel, 4 penny"
test_coin_exchange 50 "2 quarter, 0 dime, 0 nickel, 0 penny"
test_coin_exchange 51 "2 quarter, 0 dime, 0 nickel, 1 penny"
test_coin_exchange 52 "2 quarter, 0 dime, 0 nickel, 2 penny"
test_coin_exchange 53 "2 quarter, 0 dime, 0 nickel, 3 penny"
test_coin_exchange 54 "2 quarter, 0 dime, 0 nickel, 4 penny"
test_coin_exchange 55 "2 quarter, 0 dime, 1 nickel, 0 penny"
test_coin_exchange 56 "2 quarter, 0 dime, 1 nickel, 1 penny"
test_coin_exchange 57 "2 quarter, 0 dime, 1 nickel, 2 penny"
test_coin_exchange 58 "2 quarter, 0 dime, 1 nickel, 3 penny"
test_coin_exchange 59 "2 quarter, 0 dime, 1 nickel, 4 penny"
test_coin_exchange 60 "2 quarter, 1 dime, 0 nickel, 0 penny"
test_coin_exchange 61 "2 quarter, 1 dime, 0 nickel, 1 penny"
test_coin_exchange 62 "2 quarter, 1 dime, 0 nickel, 2 penny"
test_coin_exchange 63 "2 quarter, 1 dime, 0 nickel, 3 penny"
test_coin_exchange 64 "2 quarter, 1 dime, 0 nickel, 4 penny"
test_coin_exchange 65 "2 quarter, 1 dime, 1 nickel, 0 penny"
test_coin_exchange 66 "2 quarter, 1 dime, 1 nickel, 1 penny"
test_coin_exchange 67 "2 quarter, 1 dime, 1 nickel, 2 penny"
test_coin_exchange 68 "2 quarter, 1 dime, 1 nickel, 3 penny"
test_coin_exchange 69 "2 quarter, 1 dime, 1 nickel, 4 penny"
test_coin_exchange 70 "2 quarter, 2 dime, 0 nickel, 0 penny"
test_coin_exchange 71 "2 quarter, 2 dime, 0 nickel, 1 penny"
test_coin_exchange 72 "2 quarter, 2 dime, 0 nickel, 2 penny"
test_coin_exchange 73 "2 quarter, 2 dime, 0 nickel, 3 penny"
test_coin_exchange 74 "2 quarter, 2 dime, 0 nickel, 4 penny"
test_coin_exchange 75 "3 quarter, 0 dime, 0 nickel, 0 penny"
test_coin_exchange 76 "3 quarter, 0 dime, 0 nickel, 1 penny"
test_coin_exchange 77 "3 quarter, 0 dime, 0 nickel, 2 penny"
test_coin_exchange 78 "3 quarter, 0 dime, 0 nickel, 3 penny"
test_coin_exchange 79 "3 quarter, 0 dime, 0 nickel, 4 penny"
test_coin_exchange 80 "3 quarter, 0 dime, 1 nickel, 0 penny"
test_coin_exchange 81 "3 quarter, 0 dime, 1 nickel, 1 penny"
test_coin_exchange 82 "3 quarter, 0 dime, 1 nickel, 2 penny"
test_coin_exchange 83 "3 quarter, 0 dime, 1 nickel, 3 penny"
test_coin_exchange 84 "3 quarter, 0 dime, 1 nickel, 4 penny"
test_coin_exchange 85 "3 quarter, 1 dime, 0 nickel, 0 penny"
test_coin_exchange 86 "3 quarter, 1 dime, 0 nickel, 1 penny"
test_coin_exchange 87 "3 quarter, 1 dime, 0 nickel, 2 penny"
test_coin_exchange 88 "3 quarter, 1 dime, 0 nickel, 3 penny"
test_coin_exchange 89 "3 quarter, 1 dime, 0 nickel, 4 penny"
test_coin_exchange 90 "3 quarter, 1 dime, 1 nickel, 0 penny"
test_coin_exchange 91 "3 quarter, 1 dime, 1 nickel, 1 penny"
test_coin_exchange 92 "3 quarter, 1 dime, 1 nickel, 2 penny"
test_coin_exchange 93 "3 quarter, 1 dime, 1 nickel, 3 penny"
test_coin_exchange 94 "3 quarter, 1 dime, 1 nickel, 4 penny"
test_coin_exchange 95 "3 quarter, 2 dime, 0 nickel, 0 penny"
test_coin_exchange 96 "3 quarter, 2 dime, 0 nickel, 1 penny"
test_coin_exchange 97 "3 quarter, 2 dime, 0 nickel, 2 penny"
test_coin_exchange 98 "3 quarter, 2 dime, 0 nickel, 3 penny"
test_coin_exchange 99 "3 quarter, 2 dime, 0 nickel, 4 penny"
test_coin_exchange 100 "4 quarter, 0 dime, 0 nickel, 0 penny"
test_coin_exchange 101 "4 quarter, 0 dime, 0 nickel, 1 penny"
test_coin_exchange 102 "4 quarter, 0 dime, 0 nickel, 2 penny"
test_coin_exchange 103 "4 quarter, 0 dime, 0 nickel, 3 penny"
test_coin_exchange 104 "4 quarter, 0 dime, 0 nickel, 4 penny"
test_coin_exchange 105 "4 quarter, 0 dime, 1 nickel, 0 penny"
test_coin_exchange 106 "4 quarter, 0 dime, 1 nickel, 1 penny"
test_coin_exchange 107 "4 quarter, 0 dime, 1 nickel, 2 penny"
test_coin_exchange 108 "4 quarter, 0 dime, 1 nickel, 3 penny"
test_coin_exchange 109 "4 quarter, 0 dime, 1 nickel, 4 penny"
test_coin_exchange 110 "4 quarter, 1 dime, 0 nickel, 0 penny"
test_coin_exchange 111 "4 quarter, 1 dime, 0 nickel, 1 penny"
test_coin_exchange 112 "4 quarter, 1 dime, 0 nickel, 2 penny"
test_coin_exchange 113 "4 quarter, 1 dime, 0 nickel, 3 penny"
test_coin_exchange 114 "4 quarter, 1 dime, 0 nickel, 4 penny"
test_coin_exchange 115 "4 quarter, 1 dime, 1 nickel, 0 penny"
test_coin_exchange 116 "4 quarter, 1 dime, 1 nickel, 1 penny"
test_coin_exchange 117 "4 quarter, 1 dime, 1 nickel, 2 penny"
test_coin_exchange 118 "4 quarter, 1 dime, 1 nickel, 3 penny"
test_coin_exchange 119 "4 quarter, 1 dime, 1 nickel, 4 penny"
test_coin_exchange 120 "4 quarter, 2 dime, 0 nickel, 0 penny"
test_coin_exchange 121 "4 quarter, 2 dime, 0 nickel, 1 penny"
test_coin_exchange 122 "4 quarter, 2 dime, 0 nickel, 2 penny"
test_coin_exchange 123 "4 quarter, 2 dime, 0 nickel, 3 penny"
test_coin_exchange 124 "4 quarter, 2 dime, 0 nickel, 4 penny"
test_coin_exchange 125 "5 quarter, 0 dime, 0 nickel, 0 penny"
test_coin_exchange 126 "5 quarter, 0 dime, 0 nickel, 1 penny"
test_coin_exchange 127 "5 quarter, 0 dime, 0 nickel, 2 penny"
test_coin_exchange 128 "5 quarter, 0 dime, 0 nickel, 3 penny"
test_coin_exchange 129 "5 quarter, 0 dime, 0 nickel, 4 penny"
test_coin_exchange 130 "5 quarter, 0 dime, 1 nickel, 0 penny"
test_coin_exchange 131 "5 quarter, 0 dime, 1 nickel, 1 penny"
test_coin_exchange 132 "5 quarter, 0 dime, 1 nickel, 2 penny"
test_coin_exchange 133 "5 quarter, 0 dime, 1 nickel, 3 penny"
test_coin_exchange 134 "5 quarter, 0 dime, 1 nickel, 4 penny"
test_coin_exchange 135 "5 quarter, 1 dime, 0 nickel, 0 penny"
test_coin_exchange 136 "5 quarter, 1 dime, 0 nickel, 1 penny"
test_coin_exchange 137 "5 quarter, 1 dime, 0 nickel, 2 penny"
test_coin_exchange 138 "5 quarter, 1 dime, 0 nickel, 3 penny"
test_coin_exchange 139 "5 quarter, 1 dime, 0 nickel, 4 penny"
test_coin_exchange 140 "5 quarter, 1 dime, 1 nickel, 0 penny"
test_coin_exchange 141 "5 quarter, 1 dime, 1 nickel, 1 penny"
test_coin_exchange 142 "5 quarter, 1 dime, 1 nickel, 2 penny"
test_coin_exchange 143 "5 quarter, 1 dime, 1 nickel, 3 penny"
test_coin_exchange 144 "5 quarter, 1 dime, 1 nickel, 4 penny"
test_coin_exchange 145 "5 quarter, 2 dime, 0 nickel, 0 penny"
test_coin_exchange 146 "5 quarter, 2 dime, 0 nickel, 1 penny"
test_coin_exchange 147 "5 quarter, 2 dime, 0 nickel, 2 penny"
test_coin_exchange 148 "5 quarter, 2 dime, 0 nickel, 3 penny"
test_coin_exchange 149 "5 quarter, 2 dime, 0 nickel, 4 penny"
test_coin_exchange 150 "6 quarter, 0 dime, 0 nickel, 0 penny"
test_coin_exchange 151 "6 quarter, 0 dime, 0 nickel, 1 penny"






# Add more tests as needed

echo "Tests completed."
